//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activo_Fijo
    {
        public int Id_Activo { get; set; }
        public Nullable<int> Id_Categoria { get; set; }
        public string Item { get; set; }
        public string N_Serie { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> Id_Proveedor { get; set; }
        public Nullable<int> Id_Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<System.DateTime> F_Adquisicion { get; set; }
        public Nullable<System.DateTime> F_Retiro { get; set; }
        public Nullable<decimal> Precio_Adquisicion { get; set; }
        public Nullable<decimal> Valor_Actual { get; set; }
        public Nullable<int> Id_Condicion { get; set; }
        public Nullable<int> Id_Ubicacion { get; set; }
        public Nullable<int> Id_Pago { get; set; }
        public string Usuario_Asignado { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
    
        public virtual Ca_Categoria Ca_Categoria { get; set; }
        public virtual Ca_Condicion Ca_Condicion { get; set; }
        public virtual Ca_Marca Ca_Marca { get; set; }
        public virtual Ca_Oficinas Ca_Oficinas { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual Empresas Empresas1 { get; set; }
        public virtual Ca_Moneda Ca_Moneda { get; set; }
    }
}
