//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividades_Areas
    {
        public int Id_Actividades_Areas { get; set; }
        public Nullable<int> Id_Area { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> Id_Proyecto { get; set; }
        public Nullable<int> Id_Responsable { get; set; }
        public Nullable<System.DateTime> F_Init { get; set; }
        public Nullable<System.DateTime> F_Fin { get; set; }
        public Nullable<int> Id_Estatus_Actividades { get; set; }
        public Nullable<decimal> Presupuesto { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Contador { get; set; }
        public string Actividad { get; set; }
        public Nullable<System.DateTime> F_Cierre { get; set; }
        public Nullable<bool> Proyecto { get; set; }
        public Nullable<int> Id_Asigno { get; set; }
        public Nullable<int> Dias_Restantes { get; set; }
    }
}
