//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amex
    {
        public int IdAmex { get; set; }
        public int Id_Ftp { get; set; }
        public string Csv { get; set; }
        public string CsvVirtual { get; set; }
        public int Creadopor { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
