//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriaDocs
    {
        public int ID { get; set; }
        public string SP_MENU { get; set; }
        public string SP_SUBMENU { get; set; }
        public string SP_USER { get; set; }
        public string SP_FOLDER { get; set; }
        public Nullable<int> SP_FOLDER_LENGHT { get; set; }
        public string SP_FILE { get; set; }
        public Nullable<int> SP_FILE_LENGHT { get; set; }
        public Nullable<int> SP_FOLDER_INVALID_CHARS { get; set; }
        public string SP_STATUS { get; set; }
        public string SP_CPOMMENT { get; set; }
        public Nullable<int> SP_FILE_INVALID_CHARS { get; set; }
        public string SP_PATH { get; set; }
        public string SP_BACK_UP { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
    }
}
