//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avances_Actividades
    {
        public int Id_Avances_Actividad { get; set; }
        public int Id_Actividades_Areas { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> F_Actividad { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Dias_Restantes { get; set; }
    }
}
