//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_Clabe
    {
        public int Id_Clabe { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> Id_Banco { get; set; }
        public string N_Cuenta { get; set; }
        public string N_Clabe { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public Nullable<int> Id_Proyecto { get; set; }
    
        public virtual Ca_Bancos Ca_Bancos { get; set; }
        public virtual Ca_Moneda Ca_Moneda { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual Proyectos Proyectos { get; set; }
    }
}
