//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_FTP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ca_FTP()
        {
            this.Documentos_Codole = new HashSet<Documentos_Codole>();
            this.SEDocumentosServicios = new HashSet<SEDocumentosServicios>();
        }
    
        public int Id_Ftp { get; set; }
        public Nullable<int> Id_Tipo_Ftp { get; set; }
        public string URL { get; set; }
        public string Usuario { get; set; }
        public string Pass { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Ca_Tipo_FTP Ca_Tipo_FTP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos_Codole> Documentos_Codole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEDocumentosServicios> SEDocumentosServicios { get; set; }
    }
}
