//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobro_Planeacion
    {
        public int Id_Cobro_Planeacion { get; set; }
        public Nullable<int> Id_Costo { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> N_Proyectos { get; set; }
        public Nullable<decimal> CostoxProyecto { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public Nullable<System.DateTime> Anio { get; set; }
        public Nullable<System.DateTime> Mes { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
