//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CobroxServiciosxEmpresa
    {
        public int Id_CobroxServicios { get; set; }
        public Nullable<int> Id_Padre { get; set; }
        public Nullable<int> Id_Pago { get; set; }
        public Nullable<int> Id_Nivel2 { get; set; }
        public int Id_Empresa { get; set; }
        public Nullable<int> Id_Proyecto { get; set; }
        public Nullable<bool> Subsidio { get; set; }
        public Nullable<int> Id_Lapso { get; set; }
        public Nullable<System.DateTime> Fecha_Corte { get; set; }
        public Nullable<int> Id_Estatus_Cobro { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
