//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codole_Documentos
    {
        public int Id_Documento { get; set; }
        public string Nombre { get; set; }
        public string Nombre_Virtual { get; set; }
        public Nullable<int> Id_Ftp { get; set; }
        public Nullable<int> Id_Codole { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<System.DateTime> F_Inicio { get; set; }
        public Nullable<System.DateTime> F_Fin { get; set; }
        public Nullable<bool> Indefinido { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Id_Tipo_Documento { get; set; }
    }
}
