//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODOLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CODOLE()
        {
            this.Documentos_Codole = new HashSet<Documentos_Codole>();
        }
    
        public int Id_Codole { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Id_Tipo_Codole { get; set; }
        public Nullable<System.DateTime> F_Init { get; set; }
        public Nullable<System.DateTime> F_Fin { get; set; }
        public Nullable<System.DateTime> F_Firma { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Observaciones { get; set; }
        public string Encargado_Firmas { get; set; }
        public string Codigo_Codole { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> Id_Proveedor { get; set; }
        public Nullable<bool> Proyecto { get; set; }
        public Nullable<int> Id_Proyecto { get; set; }
        public Nullable<int> Id_Notaria { get; set; }
        public Nullable<int> Id_Notario { get; set; }
        public string Entregado_A { get; set; }
        public Nullable<int> Id_Medio { get; set; }
        public Nullable<System.DateTime> Fecha_Entrega { get; set; }
        public string Referencia_Entrega { get; set; }
        public string Solicitado_por { get; set; }
        public Nullable<int> Id_Valido_por { get; set; }
        public Nullable<int> Id_Generado_por { get; set; }
        public Nullable<int> Id_Notaria_Interna { get; set; }
        public Nullable<int> Id_Notario_Interno { get; set; }
        public bool Indefinido { get; set; }
        public Nullable<int> Id_Documento { get; set; }
        public Nullable<int> Id_Solicitado_por { get; set; }
    
        public virtual Ca_Tipo_Codole Ca_Tipo_Codole { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual Empresas Empresas1 { get; set; }
        public virtual Proyectos Proyectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos_Codole> Documentos_Codole { get; set; }
    }
}
