//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComparativaProveedores
    {
        public int IdTablaComparativa { get; set; }
        public string Concepto { get; set; }
        public string Justificacion { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public string NProveedor { get; set; }
        public string Direccion { get; set; }
        public string Categoria { get; set; }
        public string PesoDimensiones { get; set; }
        public string Disponibilidad { get; set; }
        public string AlcanceSeguro { get; set; }
        public string Credito { get; set; }
        public string Garantia { get; set; }
        public Nullable<double> Precio { get; set; }
        public string TerminosCondiciones { get; set; }
        public Nullable<int> IdRequisicion { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
