//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraTipoDocumento
    {
        public int IdTipoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<int> creadoPor { get; set; }
        public Nullable<System.DateTime> Falta { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
