//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comparativo_Proveedor
    {
        public int Id_Detalle_Proveedor { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> Id_Tipo_Empresa { get; set; }
        public string Descripcion_Producto { get; set; }
        public string Peso_Dimensiones { get; set; }
        public Nullable<bool> Alcance { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public Nullable<int> Tiempo_entrega { get; set; }
        public Nullable<bool> Importacion { get; set; }
        public Nullable<int> Credito { get; set; }
        public Nullable<bool> credito_Anticipo { get; set; }
        public Nullable<bool> Garantia { get; set; }
        public Nullable<int> Stock_Disponible { get; set; }
        public Nullable<int> Id_Calidad_Servicio { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<int> Creado_Por { get; set; }
        public Nullable<int> Id_Referencia { get; set; }
        public string Comentario_Referencia { get; set; }
    
        public virtual Ca_Moneda Ca_Moneda { get; set; }
        public virtual Empresas Empresas { get; set; }
    }
}
