//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comparacion_Proveedor_Temp
    {
        public int Id_Comparacion { get; set; }
        public Nullable<int> Id_Detalle_Proveedor { get; set; }
        public Nullable<int> Tiempo_Entrega_Temp { get; set; }
        public Nullable<int> Credito_Temp { get; set; }
        public Nullable<int> Id_Referencia_Temp { get; set; }
        public Nullable<int> Id_Calidad_Servicio_Temp { get; set; }
        public Nullable<int> Alcance_Temp { get; set; }
        public Nullable<int> Total_Temp { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Costo_Temp { get; set; }
    }
}
