//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class correoReqCompra
    {
        public int idCorreo { get; set; }
        public Nullable<int> IdReqCompra { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string Correo { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
