//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CsvAmex
    {
        public int IdCsvAmex { get; set; }
        public int IdAmex { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> Id_N_Cuenta { get; set; }
        public Nullable<int> Id_Clabe { get; set; }
        public Nullable<int> Id_Proyecto { get; set; }
        public Nullable<int> Id_Rubro { get; set; }
        public int IdTipoTransaccion { get; set; }
        public Nullable<int> Id_Proveedor { get; set; }
        public Nullable<int> Id_N_Cuenta_Proveedor { get; set; }
        public Nullable<int> Id_Clabe_Proveedor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> F_Movimiento { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> SaldoFinal { get; set; }
        public string Negocio { get; set; }
        public string Direccion { get; set; }
        public string Informacion { get; set; }
        public Nullable<int> Id_Pago { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public int Creadopor { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Id_CS1 { get; set; }
        public Nullable<int> Id_CS2 { get; set; }
        public Nullable<int> IdReqCompra { get; set; }
        public string Tarjeta { get; set; }
        public string TarjetaHabiente { get; set; }
    }
}
