//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresasV2
    {
        public int Id_Empresa { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> Id_Tipo_Empresa { get; set; }
        public string Razon_Social { get; set; }
        public string RFC { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Id_Programa { get; set; }
        public Nullable<int> Id_Modalidad { get; set; }
        public string CP { get; set; }
        public string Calle { get; set; }
        public string Municipio { get; set; }
        public string NoInterior { get; set; }
        public string NoExterior { get; set; }
        public string Colonia { get; set; }
        public Nullable<int> Id_Estado { get; set; }
        public Nullable<int> Id_Pais { get; set; }
        public string Localidad { get; set; }
    }
}
