//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresas()
        {
            this.TaksAdmon = new HashSet<TaksAdmon>();
            this.Ca_N_Cuenta = new HashSet<Ca_N_Cuenta>();
            this.Proyectos = new HashSet<Proyectos>();
            this.Ca_Clabe = new HashSet<Ca_Clabe>();
            this.Re_Usuario_Empresa = new HashSet<Re_Usuario_Empresa>();
            this.Re_Proveedores_Empresa = new HashSet<Re_Proveedores_Empresa>();
            this.Re_Proveedores_Empresa1 = new HashSet<Re_Proveedores_Empresa>();
            this.Activo_Fijo = new HashSet<Activo_Fijo>();
            this.Activo_Fijo1 = new HashSet<Activo_Fijo>();
            this.Capacidades_Servicios = new HashSet<Capacidades_Servicios>();
            this.Capacidades_Servicios1 = new HashSet<Capacidades_Servicios>();
            this.CaUrlSharepoint = new HashSet<CaUrlSharepoint>();
            this.CODOLE = new HashSet<CODOLE>();
            this.CODOLE1 = new HashSet<CODOLE>();
            this.Comparativo_Proveedor = new HashSet<Comparativo_Proveedor>();
            this.Contratos = new HashSet<Contratos>();
            this.MovimientosBancosCsv = new HashSet<MovimientosBancosCsv>();
            this.Rubros_Proyectos = new HashSet<Rubros_Proyectos>();
            this.SEDirecciones = new HashSet<SEDirecciones>();
            this.Servicios = new HashSet<Servicios>();
            this.Servicios1 = new HashSet<Servicios>();
            this.TrvReq = new HashSet<TrvReq>();
        }
    
        public int Id_Empresa { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> Id_Tipo_Empresa { get; set; }
        public string Razon_Social { get; set; }
        public string RFC { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> Id_Programa { get; set; }
        public Nullable<int> Id_Modalidad { get; set; }
        public string CP { get; set; }
        public string Calle { get; set; }
        public string Municipio { get; set; }
        public string NoInterior { get; set; }
        public string NoExterior { get; set; }
        public string Colonia { get; set; }
        public Nullable<int> Id_Estado { get; set; }
        public Nullable<int> Id_Pais { get; set; }
        public string Localidad { get; set; }
    
        public virtual Ca_Estado Ca_Estado { get; set; }
        public virtual Ca_Pais Ca_Pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaksAdmon> TaksAdmon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ca_N_Cuenta> Ca_N_Cuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyectos> Proyectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ca_Clabe> Ca_Clabe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Re_Usuario_Empresa> Re_Usuario_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Re_Proveedores_Empresa> Re_Proveedores_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Re_Proveedores_Empresa> Re_Proveedores_Empresa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activo_Fijo> Activo_Fijo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activo_Fijo> Activo_Fijo1 { get; set; }
        public virtual Ca_Tipo_Empresa Ca_Tipo_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Capacidades_Servicios> Capacidades_Servicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Capacidades_Servicios> Capacidades_Servicios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaUrlSharepoint> CaUrlSharepoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CODOLE> CODOLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CODOLE> CODOLE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comparativo_Proveedor> Comparativo_Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contratos> Contratos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientosBancosCsv> MovimientosBancosCsv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rubros_Proyectos> Rubros_Proyectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEDirecciones> SEDirecciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicios> Servicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicios> Servicios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrvReq> TrvReq { get; set; }
    }
}
