//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvInventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvInventario()
        {
            this.InvSolicitud = new HashSet<InvSolicitud>();
        }
    
        public int IdInventario { get; set; }
        public string Item { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public Nullable<int> IdSubTipo { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> IdUnidadMedida { get; set; }
        public Nullable<double> CostoUnitario { get; set; }
        public Nullable<double> EnExistencia { get; set; }
        public Nullable<double> Dispobibles { get; set; }
        public bool ReqDevolucion { get; set; }
        public Nullable<int> InvMin { get; set; }
        public Nullable<int> InvMax { get; set; }
        public string Imagen { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public string NombreVirtual { get; set; }
    
        public virtual InvSubTipo InvSubTipo { get; set; }
        public virtual InvTipo InvTipo { get; set; }
        public virtual InvUMedida InvUMedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvSolicitud> InvSolicitud { get; set; }
    }
}
