//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvListaPedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvListaPedidos()
        {
            this.InvSolicitud = new HashSet<InvSolicitud>();
        }
    
        public int IdListaPedido { get; set; }
        public string Descripcion { get; set; }
        public bool Atendido { get; set; }
        public int CreadoPor { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FAlta { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvSolicitud> InvSolicitud { get; set; }
    }
}
