//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvSolicitud
    {
        public int IdSolicitud { get; set; }
        public Nullable<int> IdListaPedidos { get; set; }
        public Nullable<int> IdUsuarioExpediente { get; set; }
        public int IdInventario { get; set; }
        public string Inventario { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<bool> Entregado { get; set; }
        public Nullable<bool> Devuelto { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<System.DateTime> FecgaDevolucion { get; set; }
        public Nullable<bool> NoDisponible { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Estatus { get; set; }
    
        public virtual InvInventario InvInventario { get; set; }
        public virtual InvListaPedidos InvListaPedidos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
