//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Capacidades_Servicios
    {
        public int Id_Log_Capacidades_Servicios { get; set; }
        public Nullable<int> Id_Capacidades_Servicios { get; set; }
        public Nullable<int> Id_Padre { get; set; }
        public Nullable<int> Id_Codole { get; set; }
        public Nullable<int> Id_Pago { get; set; }
        public Nullable<int> Id_Contrato { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> Id_Proveedor { get; set; }
        public Nullable<int> Id_Tipo_Servicio { get; set; }
        public Nullable<int> Id_Estatus_Servicio { get; set; }
        public Nullable<int> Id_Proyecto { get; set; }
        public string Identificador_Unico { get; set; }
        public string Portal { get; set; }
        public string Usuario { get; set; }
        public string Pass { get; set; }
        public Nullable<bool> Mantenimiento { get; set; }
        public Nullable<System.DateTime> F_Corte { get; set; }
        public Nullable<System.DateTime> F_Init { get; set; }
        public Nullable<System.DateTime> F_Fin { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<int> Id_Lapso { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public Nullable<bool> Domiciliado { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Direccion { get; set; }
        public string Comentario { get; set; }
    }
}
