//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Pagos
    {
        public int Id_Log_Pago { get; set; }
        public Nullable<int> Id_Pago { get; set; }
        public Nullable<int> Id_Estatus_Pago { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> Id_Proveedor { get; set; }
        public Nullable<int> Id_Banco { get; set; }
        public Nullable<int> Id_Clabe { get; set; }
        public Nullable<decimal> Importe_Total { get; set; }
        public Nullable<System.DateTime> F_Compromiso_Pago { get; set; }
        public Nullable<bool> Proyecto { get; set; }
        public Nullable<int> Id_Proyecto { get; set; }
        public Nullable<bool> Contrato { get; set; }
        public Nullable<int> Id_Contrato { get; set; }
        public Nullable<bool> Anticipo { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public Nullable<int> Id_Rubro { get; set; }
        public Nullable<int> Id_Iva { get; set; }
        public Nullable<decimal> Retenciones { get; set; }
        public Nullable<decimal> ISR { get; set; }
        public string Folio_Fiscal { get; set; }
        public Nullable<int> Id_N_Cuenta { get; set; }
        public Nullable<System.DateTime> Fecha_Anticipo_Factura { get; set; }
        public Nullable<decimal> Otros { get; set; }
        public Nullable<int> Id_Banco_Empresa { get; set; }
        public Nullable<int> Id_Clabe_Empresa { get; set; }
        public Nullable<int> Id_N_Cuenta_Empresa { get; set; }
        public Nullable<System.DateTime> F_Pago { get; set; }
        public string N_Transferencia { get; set; }
        public Nullable<int> Id_Tipo_Cambio { get; set; }
        public Nullable<System.DateTime> F_Emision_Factura { get; set; }
        public Nullable<int> Id_Tipo_Pago { get; set; }
        public string N_Cotizacion { get; set; }
        public string Solicitado_por { get; set; }
        public Nullable<int> Id_Clasificacion { get; set; }
        public Nullable<decimal> IVA { get; set; }
    }
}
