//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSyncSharepoint
    {
        public int IdLogSynSharepoint { get; set; }
        public int IdSistemasSh { get; set; }
        public int IdDocumento { get; set; }
        public int IdMaster { get; set; }
        public string Nombre { get; set; }
        public string Nombre_Virtual { get; set; }
        public int IdTipoDocumento { get; set; }
        public int Id_Ftp { get; set; }
        public bool Sharepoint { get; set; }
        public System.DateTime ShFalta { get; set; }
        public int ShIdUsuario { get; set; }
        public int IdUrlSharepoint { get; set; }
        public int Creado_por { get; set; }
        public System.DateTime F_Alta { get; set; }
        public bool Activo { get; set; }
    
        public virtual CaSistemasSh CaSistemasSh { get; set; }
        public virtual CaUrlSharepoint CaUrlSharepoint { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
