//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSharepoint
    {
        public int IdLogSharepoint { get; set; }
        public int IdUsuario { get; set; }
        public string URL { get; set; }
        public int IdSistemasSh { get; set; }
        public int IdDocumento { get; set; }
        public int IdTipoDocumento { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<int> Creadopor { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
