//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manuales
    {
        public int IdManual { get; set; }
        public string Nombre { get; set; }
        public string NombreVirtual { get; set; }
        public string Descripcion { get; set; }
        public int IdMenu { get; set; }
        public int IdArea { get; set; }
        public int IdTipoUsuario { get; set; }
        public System.DateTime FAlta { get; set; }
        public System.DateTime FActualizacion { get; set; }
        public int CreadoPor { get; set; }
        public bool Activo { get; set; }
        public string NombreDoc { get; set; }
    
        public virtual CA_Areas CA_Areas { get; set; }
        public virtual ManualesTipoUsuarios ManualesTipoUsuarios { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
