//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosBancosCsv
    {
        public int IdRegistro { get; set; }
        public int Id_Banco { get; set; }
        public int Id_Empresa { get; set; }
        public int Id_N_Cuenta { get; set; }
        public int IdCsv { get; set; }
        public int IdTipoTransaccion { get; set; }
        public string Movimiento { get; set; }
        public string Transaccion { get; set; }
        public string Concepto { get; set; }
        public System.DateTime F_Movimiento { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public int Id_Moneda { get; set; }
        public decimal Saldo { get; set; }
        public Nullable<int> Id_Pago { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> F_Match { get; set; }
        public Nullable<int> Usuario_Match { get; set; }
        public Nullable<System.DateTime> FMovimientoV { get; set; }
    
        public virtual Ca_Bancos Ca_Bancos { get; set; }
        public virtual Ca_Moneda Ca_Moneda { get; set; }
        public virtual Ca_N_Cuenta Ca_N_Cuenta { get; set; }
        public virtual Csv Csv { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual TipoTransaccion TipoTransaccion { get; set; }
    }
}
