//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsFeed
    {
        public int IdItem { get; set; }
        public int Orden { get; set; }
        public string Cabecera { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public string URL { get; set; }
        public int IdTipoNoticia { get; set; }
        public bool Mostrar { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FAlta { get; set; }
    
        public virtual TipoNoticia TipoNoticia { get; set; }
    }
}
