//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomenclaturaCalidad
    {
        public int IdCalidad { get; set; }
        public string Nomenclatura { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> Orden { get; set; }
    }
}
