//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_Compra_Detalle
    {
        public int Id_Orden_Compra_Detalle { get; set; }
        public Nullable<int> Id_Orden_Compra { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Modelo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio_Unitario { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Creado_Por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
    }
}
