//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompra
    {
        public int IdOCompra { get; set; }
        public Nullable<int> IdReqCompra { get; set; }
        public Nullable<System.DateTime> FExpedicion { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<System.DateTime> FEntrega { get; set; }
        public string Contacto { get; set; }
        public string LugarEntrega { get; set; }
        public string Correo { get; set; }
        public string CondicionesPago { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Observaciones { get; set; }
        public string DatosEmpresa { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Terminos { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> RetIva { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> ISR { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
