//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_Compra
    {
        public int Id_Orden_Compra { get; set; }
        public Nullable<int> Id_Requisicion_Compra { get; set; }
        public Nullable<System.DateTime> F_Expedicion { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<System.DateTime> F_Entrega { get; set; }
        public string Contacto { get; set; }
        public string Lugar_Entrega { get; set; }
        public string Correo { get; set; }
        public string Condiciones_Pago { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Observaciones { get; set; }
        public string Proveedor { get; set; }
        public Nullable<int> Creado_Por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public string Id_Proveedor { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Terminos { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> RetIva { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> ISR { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Requisicion_Compra Requisicion_Compra { get; set; }
    }
}
