//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pagos()
        {
            this.Autorizaciones_Pago = new HashSet<Autorizaciones_Pago>();
        }
    
        public int Id_Pago { get; set; }
        public Nullable<int> Id_Estatus_Pago { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> Id_Proveedor { get; set; }
        public Nullable<int> Id_Banco { get; set; }
        public Nullable<int> Id_Clabe { get; set; }
        public Nullable<decimal> Importe_Total { get; set; }
        public Nullable<System.DateTime> F_Compromiso_Pago { get; set; }
        public Nullable<bool> Proyecto { get; set; }
        public Nullable<int> Id_Proyecto { get; set; }
        public Nullable<bool> Contrato { get; set; }
        public Nullable<int> Id_Contrato { get; set; }
        public bool Anticipo { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public Nullable<int> Id_Rubro { get; set; }
        public Nullable<int> Id_Iva { get; set; }
        public Nullable<decimal> Retenciones { get; set; }
        public Nullable<decimal> ISR { get; set; }
        public string Folio_Fiscal { get; set; }
        public Nullable<int> Id_N_Cuenta { get; set; }
        public Nullable<System.DateTime> Fecha_Anticipo_Factura { get; set; }
        public Nullable<decimal> Otros { get; set; }
        public Nullable<int> Id_Banco_Empresa { get; set; }
        public Nullable<int> Id_Clabe_Empresa { get; set; }
        public Nullable<int> Id_N_Cuenta_Empresa { get; set; }
        public Nullable<System.DateTime> F_Pago { get; set; }
        public string N_Transferencia { get; set; }
        public Nullable<int> Id_Tipo_Cambio { get; set; }
        public Nullable<System.DateTime> F_Emision_Factura { get; set; }
        public Nullable<int> Id_Tipo_Pago { get; set; }
        public string N_Cotizacion { get; set; }
        public string Solicitado_por { get; set; }
        public Nullable<int> Id_Clasificacion { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<int> Id_CS1 { get; set; }
        public Nullable<int> Id_CS2 { get; set; }
        public Nullable<int> NURC_CONTA { get; set; }
        public Nullable<int> Id_CS3 { get; set; }
        public Nullable<int> Id_CS4 { get; set; }
        public Nullable<int> Id_CS5 { get; set; }
        public Nullable<int> Id_Solicitado_por { get; set; }
        public string Apartado { get; set; }
        public string Justificacion { get; set; }
        public string N_Factura { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public Nullable<bool> Factura { get; set; }
        public Nullable<bool> XML_Factura { get; set; }
        public Nullable<bool> Val_Sat { get; set; }
        public Nullable<bool> Comprobante_Pago { get; set; }
        public Nullable<bool> EXCEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autorizaciones_Pago> Autorizaciones_Pago { get; set; }
        public virtual Ca_Bancos Ca_Bancos { get; set; }
        public virtual Ca_Bancos Ca_Bancos1 { get; set; }
        public virtual Ca_Moneda Ca_Moneda { get; set; }
        public virtual Ca_N_Cuenta Ca_N_Cuenta { get; set; }
        public virtual Ca_N_Cuenta Ca_N_Cuenta1 { get; set; }
        public virtual Ca_Rubros Ca_Rubros { get; set; }
        public virtual Ca_Solicitado_por Ca_Solicitado_por { get; set; }
    }
}
