//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAmex
    {
        public int IdPaso { get; set; }
        public int IdCsvAmex { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<int> Creadopor { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
