//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partes
    {
        public int Id_Parte { get; set; }
        public Nullable<int> Id_Contrato { get; set; }
        public string Nombre_Completo { get; set; }
        public Nullable<int> Id_Tipo_Parte { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<bool> Firma { get; set; }
        public string Cargo { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> F_Init { get; set; }
        public Nullable<System.DateTime> F_Fin { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
