//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Re_Requisicion_Preguntas_Proveedor
    {
        public int Id_Relacion_Pregunta { get; set; }
        public Nullable<int> Id_Evaluacion { get; set; }
        public Nullable<int> Id_Pregunta { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
