//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Re_Usuario_Empresa
    {
        public int Id_Re_Usuario_Empresas { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public bool Activo { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
