//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroActividades
    {
        public int Id_Actividad { get; set; }
        public string Actividad { get; set; }
        public string Descripcion_Actividad { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<int> Creado_Por { get; set; }
        public string Id_Documento { get; set; }
        public Nullable<int> Id_Area { get; set; }
        public Nullable<System.DateTime> F_Inicio { get; set; }
        public Nullable<System.DateTime> F_Fin { get; set; }
        public Nullable<double> Horas { get; set; }
        public Nullable<int> Id_Hora { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public string Socio { get; set; }
        public Nullable<int> Id_Solicitado_Por { get; set; }
        public Nullable<int> Id_Socio { get; set; }
    }
}
