//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqCompraDetalle
    {
        public int IdReqCompraDetalle { get; set; }
        public Nullable<int> IdReqCompra { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<int> IdUnidadMedida { get; set; }
        public string Producto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Creado_Por { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string contacto { get; set; }
        public string correo { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<double> montototal { get; set; }
    }
}
