//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqCompra
    {
        public int IdReqCompra { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<int> IdArea { get; set; }
        public string Correo { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<bool> AplicaProyecto { get; set; }
        public string Direccion { get; set; }
        public Nullable<bool> CertificadoCalidad { get; set; }
        public string CualCertificado { get; set; }
        public Nullable<bool> DocumentoAdicional { get; set; }
        public string CualDocumento { get; set; }
        public Nullable<bool> UsoStock { get; set; }
        public Nullable<System.DateTime> VigenciaCotizacion { get; set; }
        public Nullable<int> Id_Status { get; set; }
        public string DatosProyecto { get; set; }
        public string Justificacion { get; set; }
        public string Observaciones { get; set; }
        public string NombreSolicita { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> AutSocio { get; set; }
        public Nullable<bool> AutEjecutivo { get; set; }
        public Nullable<bool> AutDirector { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> Servicio { get; set; }
        public Nullable<int> FirmaAutorizado { get; set; }
        public Nullable<double> PrecioTotal { get; set; }
        public bool CostoInterno { get; set; }
    }
}
