//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reqFacturasDetalle
    {
        public int IdReqFacturaDetalle { get; set; }
        public Nullable<int> IdReqFactura { get; set; }
        public string Item { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> PrecioUnitario { get; set; }
        public Nullable<double> ImporteTotal { get; set; }
        public Nullable<int> unidad { get; set; }
        public Nullable<int> moneda { get; set; }
    }
}
