//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqFacturas
    {
        public int IdReqFactura { get; set; }
        public Nullable<System.DateTime> FSolcitud { get; set; }
        public Nullable<int> TipoSolicitud { get; set; }
        public Nullable<int> IdEmpresaSol { get; set; }
        public Nullable<bool> CreditoDirGeneralSol { get; set; }
        public Nullable<int> CondicionesPagoSol { get; set; }
        public string TelefonoSol { get; set; }
        public string correoSol { get; set; }
        public Nullable<int> IdNCuentaSol { get; set; }
        public Nullable<int> IdEmpresaCli { get; set; }
        public string TelefonoCli { get; set; }
        public string CorreoCli { get; set; }
        public Nullable<int> IdNCuentaCli { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> Total { get; set; }
        public string MontoConLetra { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> Autorizado { get; set; }
        public Nullable<System.DateTime> FCierre { get; set; }
        public string FolioFiscal { get; set; }
        public Nullable<int> FirmadoPor { get; set; }
        public Nullable<int> clabeSol { get; set; }
        public Nullable<int> clabeCli { get; set; }
        public string nombreSolicitante { get; set; }
        public Nullable<int> CusoCFDI { get; set; }
        public Nullable<int> CaMetodoPago { get; set; }
        public Nullable<int> FormaPago { get; set; }
        public Nullable<int> TipoPersona { get; set; }
    }
}
