//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisicion_Evaluacion_Proveedor
    {
        public int Id_Evaluacion { get; set; }
        public Nullable<int> Razon_Social { get; set; }
        public Nullable<int> Contacto { get; set; }
        public string Producto_Servicio { get; set; }
        public string Sector_Control_Responsable { get; set; }
        public Nullable<int> Creado_Por { get; set; }
        public Nullable<int> Aprobo { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<int> Id_Requisicion { get; set; }
        public string Contactos { get; set; }
    }
}
