//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisicion_Compra_Detalle
    {
        public int Id_Requisicion_Compra_Detalle { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Id_Unidad_Medida { get; set; }
        public string Producto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Creado_Por { get; set; }
        public Nullable<int> Id_Requisicion_Compra { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public string Id_Empresa { get; set; }
    
        public virtual Requisicion_Compra Requisicion_Compra { get; set; }
    }
}
