//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisicion_Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisicion_Compra()
        {
            this.Orden_Compra = new HashSet<Orden_Compra>();
            this.Requisicion_Autorizacion = new HashSet<Requisicion_Autorizacion>();
            this.Requisicion_Compra_Detalle = new HashSet<Requisicion_Compra_Detalle>();
            this.Requisicion_Compra_Proveedor = new HashSet<Requisicion_Compra_Proveedor>();
        }
    
        public int Id_Requisicion_Compra { get; set; }
        public Nullable<System.DateTime> F_Entrega { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<int> Id_Area { get; set; }
        public Nullable<int> Creado_Por { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public string Datos_Proyecto { get; set; }
        public string Observaciones { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> F_Solicitud { get; set; }
        public string Nombre_Responsable { get; set; }
        public string Justificacion { get; set; }
        public Nullable<int> Id_Status { get; set; }
        public string Correo_Responsable { get; set; }
    
        public virtual Ca_Status_Requisicion Ca_Status_Requisicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden_Compra> Orden_Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisicion_Autorizacion> Requisicion_Autorizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisicion_Compra_Detalle> Requisicion_Compra_Detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisicion_Compra_Proveedor> Requisicion_Compra_Proveedor { get; set; }
    }
}
