//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsable_Proyecto
    {
        public int Id_Responsable_Proyecto { get; set; }
        public Nullable<int> Id_Solicitado_por { get; set; }
        public Nullable<int> Id_Proyecto { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Ca_Solicitado_por Ca_Solicitado_por { get; set; }
        public virtual Proyectos Proyectos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
