//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RH_Documentos
    {
        public int IdDocumento { get; set; }
        public string Nombre { get; set; }
        public string NombreVirtual { get; set; }
        public Nullable<int> IdFtp { get; set; }
        public Nullable<int> Creadopor { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdTipo_Documento { get; set; }
        public Nullable<int> IdUsuarioExpediente { get; set; }
        public Nullable<int> IdUsuarioVacante { get; set; }
        public Nullable<int> Enviado { get; set; }
        public Nullable<int> NAdicional { get; set; }
    }
}
