//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RH_Expediente
    {
        public int IdUsuarioExpediente { get; set; }
        public string NombreTrabajador { get; set; }
        public string Nss { get; set; }
        public string TelefonoCasa { get; set; }
        public string TelefonoCelular { get; set; }
        public string NombreContacto { get; set; }
        public Nullable<int> Parentesco { get; set; }
        public string TelefonoContacto { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<System.DateTime> FIngreso { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<int> IdGin { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<bool> NAdicional { get; set; }
        public string pin { get; set; }
    }
}
