//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RhDocumentosImpuesto
    {
        public int IdDocumentoNomina { get; set; }
        public Nullable<int> IdImpuestoNomina { get; set; }
        public string Nombre { get; set; }
        public string NombreVirtual { get; set; }
        public Nullable<int> IdFtp { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
    }
}
