//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RHExpedienteEmpleado
    {
        public int IdUsuarioExpediente { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string NombreEmpleado { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Curp { get; set; }
        public string RFC { get; set; }
        public Nullable<bool> Casado { get; set; }
        public string Nss { get; set; }
        public string Telefono { get; set; }
        public string NombreContacto { get; set; }
        public string TelefonoContacto { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<System.DateTime> FPlanta { get; set; }
        public Nullable<System.DateTime> FBaja { get; set; }
        public Nullable<System.DateTime> FActualizacion { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<int> IdPuesto { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> pin { get; set; }
    }
}
