//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RhLogConfiguracionCorreos
    {
        public int IdLogConfiguracion { get; set; }
        public int IdConfiguracion { get; set; }
        public Nullable<int> IdTipoCorreo { get; set; }
        public string Correo { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<System.DateTime> FEnvio { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    }
}
