//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RhLogConfiguraExcel
    {
        public int IdLogGeneraDoc { get; set; }
        public int IdGeneraDoc { get; set; }
        public Nullable<int> IdTipoCorreo { get; set; }
        public string TipoNomina { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<int> Activo { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> Finicio { get; set; }
        public Nullable<System.DateTime> FFin { get; set; }
    }
}
