//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RhLogVacaciones
    {
        public int IdLogVacaciones { get; set; }
        public int IdVacaciones { get; set; }
        public Nullable<int> IdUsuarioExpediente { get; set; }
        public Nullable<System.DateTime> FIngreso { get; set; }
        public Nullable<int> SueldoDiario { get; set; }
        public Nullable<System.DateTime> FInicio { get; set; }
        public Nullable<System.DateTime> FFin { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<int> IdVacacionAutorizacion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> DiasRestantes { get; set; }
        public Nullable<int> DiasDisponibles { get; set; }
        public Nullable<System.DateTime> DiaPresentarse { get; set; }
    }
}
