//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RhNomina
    {
        public int IdNomina { get; set; }
        public Nullable<int> IdUsuarioExpediente { get; set; }
        public Nullable<double> SueldoMensual { get; set; }
        public Nullable<double> SueldoDiario { get; set; }
        public Nullable<System.DateTime> FIngreso { get; set; }
        public Nullable<double> Dias { get; set; }
        public Nullable<double> SueldoQuincenal { get; set; }
        public Nullable<double> Bonos { get; set; }
        public Nullable<double> Vacaciones { get; set; }
        public Nullable<double> PrimaVacacional { get; set; }
        public Nullable<double> Aguinaldo { get; set; }
        public Nullable<double> TotalPercepciones { get; set; }
        public Nullable<double> Isr { get; set; }
        public Nullable<double> Prestamo { get; set; }
        public Nullable<double> CreditoInfonavit { get; set; }
        public Nullable<double> TotalDeducciones { get; set; }
        public Nullable<double> TotalDeposito { get; set; }
        public Nullable<double> CargaSocial { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<int> IdGin { get; set; }
        public Nullable<int> IdTotal { get; set; }
        public Nullable<int> TipoNomina { get; set; }
        public Nullable<System.DateTime> FNInicio { get; set; }
        public Nullable<System.DateTime> FNFin { get; set; }
        public Nullable<int> Nnomina { get; set; }
        public Nullable<double> Finiquito { get; set; }
        public Nullable<double> OtrasDeducciones { get; set; }
    }
}
