//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RhTotalNomina
    {
        public int IdTotal { get; set; }
        public Nullable<double> TNomina { get; set; }
        public Nullable<double> TBonos { get; set; }
        public Nullable<double> TVacaciones { get; set; }
        public Nullable<double> TPrimaVacacional { get; set; }
        public Nullable<double> TAguinaldo { get; set; }
        public Nullable<double> TTotalDePercepciones { get; set; }
        public Nullable<double> TFiniquito { get; set; }
        public Nullable<double> TIsr { get; set; }
        public Nullable<double> TPrestamo { get; set; }
        public Nullable<double> TCreditoInfonavit { get; set; }
        public Nullable<double> TTotalDeducciones { get; set; }
        public Nullable<double> TTotalDeposito { get; set; }
        public Nullable<double> TCargaSocial { get; set; }
        public Nullable<double> TTBonos { get; set; }
        public Nullable<double> TSubtotal { get; set; }
        public Nullable<double> Honorario { get; set; }
        public Nullable<double> TImss { get; set; }
        public Nullable<double> TTSubtotal { get; set; }
        public Nullable<double> TOtrasDeducciones { get; set; }
        public Nullable<double> Tiva { get; set; }
        public Nullable<double> TFactura { get; set; }
        public Nullable<int> TipoQuincena { get; set; }
        public Nullable<double> SGMM { get; set; }
    }
}
