//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RhVacantes
    {
        public int IdVacante { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<double> ApegoPerfil { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public string Coimentarios { get; set; }
        public Nullable<int> TomarEnCuenta { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> Aceptado { get; set; }
        public string Puesto { get; set; }
    }
}
