//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEDirecciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEDirecciones()
        {
            this.Servicios = new HashSet<Servicios>();
        }
    
        public int IdDireccion { get; set; }
        public int Id_tipo_servicio { get; set; }
        public int Id_Proveedor { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Ca_Tipo_Servicio Ca_Tipo_Servicio { get; set; }
        public virtual Empresas Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicios> Servicios { get; set; }
    }
}
