//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEDocumentosServicios
    {
        public int IdDocumentoServicio { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public int IdTipoDocumentoServicio { get; set; }
        public string Nombre { get; set; }
        public string NombreVirtual { get; set; }
        public int Id_FTP { get; set; }
        public System.DateTime FAlta { get; set; }
        public int CreadoPor { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> IdSistemasSh { get; set; }
        public Nullable<bool> Sharepoint { get; set; }
        public Nullable<System.DateTime> ShFalta { get; set; }
        public Nullable<int> ShIdUsuario { get; set; }
    
        public virtual Ca_FTP Ca_FTP { get; set; }
        public virtual SETipoDocumento SETipoDocumento { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
