//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELogServicios
    {
        public int IdLogSeServicios { get; set; }
        public int IdServicios { get; set; }
        public int IdEstatusServicio { get; set; }
        public int Id_tipo_servicio { get; set; }
        public int Id_Lapso { get; set; }
        public int Id_Empresa { get; set; }
        public int Id_Proveedor { get; set; }
        public string NReferencia { get; set; }
        public System.DateTime Anio { get; set; }
        public System.DateTime Mes { get; set; }
        public System.DateTime FCorte { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public string Comentario { get; set; }
        public Nullable<bool> Factura { get; set; }
        public Nullable<bool> XML { get; set; }
        public Nullable<bool> CPago { get; set; }
        public Nullable<bool> Excel { get; set; }
        public Nullable<bool> Otros { get; set; }
        public Nullable<int> Id_Pago { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdDireccion { get; set; }
    }
}
