//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaksAdmon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaksAdmon()
        {
            this.TaksComentarios = new HashSet<TaksComentarios>();
            this.TaksPertenencia = new HashSet<TaksPertenencia>();
            this.TaksDocumentos = new HashSet<TaksDocumentos>();
        }
    
        public int IdTaks { get; set; }
        public int IdEstatusTaks { get; set; }
        public int IdTaksTipo { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public int Id_Empresa { get; set; }
        public string Asunto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FSolicitud { get; set; }
        public Nullable<System.DateTime> FCierre { get; set; }
        public string Empresa { get; set; }
        public string Proveedor { get; set; }
        public string RFCProveedor { get; set; }
        public string BancoProveedor { get; set; }
        public string NCuentaProveedor { get; set; }
        public string ClabeProveedor { get; set; }
        public string SWIFT { get; set; }
        public string IBAN { get; set; }
        public string Sucursal { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public Nullable<System.DateTime> FCompromisoPago { get; set; }
        public Nullable<int> Id_Proyecto { get; set; }
        public Nullable<bool> ContratoProveedor { get; set; }
        public Nullable<int> Id_Rubro { get; set; }
        public string ContactoProveedor { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public System.DateTime FAlta { get; set; }
        public int Creadopor { get; set; }
        public bool Activo { get; set; }
        public Nullable<bool> Anticipo { get; set; }
        public Nullable<int> IdUsuarioS { get; set; }
        public Nullable<int> IdAtencion { get; set; }
        public Nullable<int> Id_Pago { get; set; }
        public Nullable<int> Id_CA_Area { get; set; }
    
        public virtual CA_Areas CA_Areas { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual TaksEstatus TaksEstatus { get; set; }
        public virtual TaksTipo TaksTipo { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaksComentarios> TaksComentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaksPertenencia> TaksPertenencia { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaksDocumentos> TaksDocumentos { get; set; }
    }
}
