//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_cs
    {
        public int NURC_PAGOS { get; set; }
        public Nullable<int> Id_CS1 { get; set; }
        public Nullable<int> Id_CS2 { get; set; }
        public Nullable<int> Id_CS3 { get; set; }
        public Nullable<int> Id_CS4 { get; set; }
        public Nullable<int> Id_CS5 { get; set; }
        public Nullable<bool> Replicado { get; set; }
    }
}
