//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Actividades_Reporte
    {
        public int IdTempActividad { get; set; }
        public Nullable<double> Hora { get; set; }
        public Nullable<double> Minutos { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> Solicitado_Por { get; set; }
        public Nullable<double> TiempoTotal { get; set; }
        public Nullable<int> Usuario { get; set; }
        public Nullable<double> Porcentaje { get; set; }
        public string Socio { get; set; }
    }
}
