//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Ti
    {
        public int Id_Formato { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<int> Creado_Por { get; set; }
        public Nullable<int> Id_Area { get; set; }
        public Nullable<int> Id_Tipo_Servicio { get; set; }
        public string Descripcion_Problema { get; set; }
        public string Diagnostico { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Id_Usuario_Atendio { get; set; }
        public Nullable<int> Id_Usuario_Soluciono { get; set; }
        public Nullable<System.DateTime> F_Fin { get; set; }
        public Nullable<int> Id_Status { get; set; }
        public Nullable<int> Id_Documento { get; set; }
        public string Otro_servicio { get; set; }
    }
}
