//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoNoticia
    {
        public int IdTipo { get; set; }
        public string TipoNoticia1 { get; set; }
        public System.DateTime FAta { get; set; }
    
        public virtual NewsFeed NewsFeed { get; set; }
    }
}
