//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrvReq
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrvReq()
        {
            this.TrvRepConceptos = new HashSet<TrvRepConceptos>();
        }
    
        public int IdTrvReq { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public int IdEstatus { get; set; }
        public Nullable<int> IdTransporte { get; set; }
        public string Origen { get; set; }
        public string PaisDes { get; set; }
        public string Destino { get; set; }
        public System.DateTime FPartida { get; set; }
        public System.DateTime FRetorno { get; set; }
        public decimal MViaticos { get; set; }
        public string Motivo { get; set; }
        public bool Aprobado { get; set; }
        public string Comentario { get; set; }
        public System.DateTime FAlta { get; set; }
        public int Creadopor { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> IdTrvTurno { get; set; }
        public Nullable<int> Id_Proyecto { get; set; }
        public Nullable<bool> GrupoTrabajo { get; set; }
        public string Necesidades { get; set; }
    
        public virtual TrvEstatus TrvEstatus { get; set; }
        public virtual TrvTransporte TrvTransporte { get; set; }
        public virtual TrvTurno TrvTurno { get; set; }
        public virtual Empresas Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrvRepConceptos> TrvRepConceptos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
