//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Rubros_Proyecto
    {
        public int Id_Rubros_Proyectos { get; set; }
        public int Id_Proyecto { get; set; }
        public string Codigo_Proyecto { get; set; }
        public string Proyecto { get; set; }
        public int Id_Empresa { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> Id_Rubro { get; set; }
        public string Codigo_Rubro { get; set; }
        public string Rubro { get; set; }
        public Nullable<decimal> Presupuesto_Interno { get; set; }
        public Nullable<decimal> Presupuesto_Externo { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public string Moneda { get; set; }
        public Nullable<int> Creado_por { get; set; }
        public string Nombre_Usuario { get; set; }
        public Nullable<System.DateTime> F_Alta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Gastado { get; set; }
        public Nullable<decimal> DIF { get; set; }
        public Nullable<decimal> Financiamiento { get; set; }
    }
}
